### ISSUE TITLE
502 when accessing definitions for Maven entities in dev

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#124]
With F12 tools open on the browse page of dev.cd.io, select the maven package com.facebook.nifty/nifty/0.23.0

Notice the 502 error POSTing to https://dev-api.clearlydefined.io/definitions with a body of ["maven/mavencentral/com.facebook.nifty/nifty-client/0.23.0"].

This happens with other Maven entities but NPMs work fine.

**Comment by geneh** [comment]
Possible solution: https://github.com/Azure/azure-storage-node/issues/304

Stack trace:
```
2018-03-07T06:28:34.729607313Z [0mPOST /definitions [32m200 [0m800.284 ms - 653[0m
2018-03-07T06:28:34.749997024Z 
2018-03-07T06:28:34.750046525Z /opt/service/node_modules/applicationinsights/out/AutoCollection/Exceptions.js:33
2018-03-07T06:28:34.750097327Z                         throw error;
2018-03-07T06:28:34.750113927Z                         ^
2018-03-07T06:28:34.750126328Z StorageError: The specified block list is invalid.
2018-03-07T06:28:34.750138428Z RequestId:a5598354-b01e-0060-7cdd-b51819000000
2018-03-07T06:28:34.750150528Z Time:2018-03-07T06:28:34.7229663Z
2018-03-07T06:28:34.750162529Z     at Function.StorageServiceClient._normalizeError (/opt/service/node_modules/azure-storage/lib/common/services/storageserviceclient.js:1191:23)
2018-03-07T06:28:34.750175329Z     at Object.StorageServiceClient._processResponse (/opt/service/node_modules/azure-storage/lib/common/services/storageserviceclient.js:738:50)
2018-03-07T06:28:34.750187830Z     at Request.processResponseCallback [as _callback] (/opt/service/node_modules/azure-storage/lib/common/services/storageserviceclient.js:311:37)
2018-03-07T06:28:34.750200530Z     at Request.self.callback (/opt/service/node_modules/request/request.js:188:22)
2018-03-07T06:28:34.750213030Z     at ZoneDelegate.invokeTask (/opt/service/node_modules/zone.js/dist/zone-node.js:275:35)
2018-03-07T06:28:34.750225331Z     at Zone.runTask (/opt/service/node_modules/zone.js/dist/zone-node.js:151:47)
2018-03-07T06:28:34.750237531Z     at Request.ZoneTask.invoke (/opt/service/node_modules/zone.js/dist/zone-node.js:345:33)
2018-03-07T06:28:34.750249831Z     at emitTwo (events.js:126:13)
2018-03-07T06:28:34.750261732Z     at Request.emit (events.js:214:7)
2018-03-07T06:28:34.750273632Z     at Request.<anonymous> (/opt/service/node_modules/request/request.js:1171:10)
2018-03-07T06:28:34.750286133Z     at ZoneDelegate.invokeTask (/opt/service/node_modules/zone.js/dist/zone-node.js:275:35)
2018-03-07T06:28:34.750298333Z     at Zone.runTask (/opt/service/node_modules/zone.js/dist/zone-node.js:151:47)
2018-03-07T06:28:34.750322934Z     at Request.ZoneTask.invoke (/opt/service/node_modules/zone.js/dist/zone-node.js:345:33)
2018-03-07T06:28:34.750336234Z     at emitOne (events.js:116:13)
2018-03-07T06:28:34.750348134Z     at Request.emit (events.js:211:7)
2018-03-07T06:28:34.764822168Z npm ERR! code ELIFECYCLE
2018-03-07T06:28:34.765452787Z npm ERR! errno 7
2018-03-07T06:28:34.767425846Z npm ERR! service@0.1.0 start: `node ./bin/www`
2018-03-07T06:28:34.767734556Z npm ERR! Exit status 7
2018-03-07T06:28:34.768342974Z npm ERR! 
2018-03-07T06:28:34.768364175Z npm ERR! Failed at the service@0.1.0 start script.
2018-03-07T06:28:34.768671584Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-03-07T06:28:34.779716115Z 
2018-03-07T06:28:34.779884720Z npm ERR! A complete log of this run can be found in:
2018-03-07T06:28:34.796246010Z npm ERR!     /root/.npm/_logs/2018-03-07T06_28_34_774Z-debug.log
```
