### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'electionId') during service startup

### ISSUE THREAD

**Issue by qtomlinson** [clearlydefined/service#1257]
During service startup, "TypeError: Cannot read properties of undefined (reading 'electionId')" is observed while connecting to DB.
```
2024-12-12T19:19:48.9569976Z TypeError: Cannot read properties of undefined (reading 'electionId')
2024-12-12T19:19:48.9570006Z     at ReplSetState.update (/opt/service/node_modules/mongodb-core/lib/topologies/replset_state.js:464:71)
2024-12-12T19:19:48.9570035Z     at /opt/service/node_modules/mongodb-core/lib/topologies/replset.js:318:47
2024-12-12T19:19:48.9570069Z     at applyAuth (/opt/service/node_modules/mongodb-core/lib/topologies/replset.js:745:43)
2024-12-12T19:19:48.9570098Z     at /opt/service/node_modules/mongodb-core/lib/topologies/replset.js:752:7
2024-12-12T19:19:48.9570147Z     at /opt/service/node_modules/mongodb-core/lib/connection/pool.js:869:7
2024-12-12T19:19:48.9570176Z     at /opt/service/node_modules/mongodb-core/lib/connection/pool.js:847:11
2024-12-12T19:19:48.9570205Z     at finish (/opt/service/node_modules/mongodb-core/lib/auth/scram.js:229:16)
2024-12-12T19:19:48.9570235Z     at handleEnd (/opt/service/node_modules/mongodb-core/lib/auth/scram.js:243:7)
2024-12-12T19:19:48.9570262Z     at /opt/service/node_modules/mongodb-core/lib/auth/scram.js:348:19
2024-12-12T19:19:48.9570291Z     at /opt/service/node_modules/mongodb-core/lib/connection/pool.js:532:18
```
Details see attached [exception details](https://github.com/user-attachments/files/18128537/serviceException_attachment.txt)

**Comment by qtomlinson** [comment]
This [StackExchange](https://stackoverflow.com/questions/44148718/azure-cosmos-db-typeerror-cannot-read-property-electionid-of-undefined) suggests "removing the &replicaSet=globaldb from the connection string if you are not using a replica set and only have a single Cosmos DB instance." A similar issue could be found at [MongoError: Pool Destroyed](https://learn.microsoft.com/en-us/archive/msdn-technet-forums/a6f76f08-903e-49a1-8e6b-3fcd17e0d981), which seemed to be also resolved by the connection string change.  
MongoError: server instance pool was destroyed is also logged as one of the top exceptions on Nov 19 in our deployments.

**Comment by qtomlinson** [comment]
@elrayle Thanks for putting in the fix!
