### ISSUE TITLE
500 error response for a given definition query

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#184]
The `"npm/npmjs/-/co/4.6.0"` coordinate is causing this issue, but it is not the only input that is causing it. Added the other, working coordinate (`"npm/npmjs/-/raw-body/2.3.3"`) to the issue for demonstration

### Steps to reproduce

1. POST to https://api.clearlydefined.io/definitions

```
[
  "npm/npmjs/-/raw-body/2.3.3",
  "npm/npmjs/-/co/4.6.0"
]
```

### Expected result

```
{
    "npm/npmjs/-/raw-body/2.3.3": {
        "described": {
            ...
        },
        "licensed": {
            ...
        },
        "files": [
            ...
        ],
        "coordinates": {
            ...
        }
    },
    "npm/npmjs/-/co/4.6.0": {
        "described": {
            ...
        },
        "licensed": {
            ...
        },
        "files": [
            ...
        ],
        "coordinates": {
            ...
        }
    }
}
```

### Actual result

```
{
    "error": {
        "code": "500",
        "message": "Unknown\nInvalid Version: undefined",
        "innererror": {}
    }
}
```

### Notes

 - We should track down the error with this specific package (co v4.6.0) and fix it
 - We should not error out the entire payload when there is 1 bad package

**Comment by dabutvin** [comment]
this error message is originating from the SemVer library, going unhandled, and bubbling up to general catch-all error handler

```
TypeError: Invalid Version: undefined
    at new SemVer (/Users/dan/codes/clearlydefined/service/node_modules/semver/semver.js:293:11)
    at compare (/Users/dan/codes/clearlydefined/service/node_modules/semver/semver.js:566:10)
    at Function.gt (/Users/dan/codes/clearlydefined/service/node_modules/semver/semver.js:595:10)
    at versions.filter.reduce (/Users/dan/codes/clearlydefined/service/lib/utils.js:39:39)
    at Array.reduce (<anonymous>)
    at Object.getLatestVersion (/Users/dan/codes/clearlydefined/service/lib/utils.js:39:6)
    at AggregationService.findData (/Users/dan/codes/clearlydefined/service/business/aggregator.js:65:26)
    at order.forEach.tool (/Users/dan/codes/clearlydefined/service/business/aggregator.js:47:25)
    at Array.forEach (<anonymous>)
    at AggregationService.process (/Users/dan/codes/clearlydefined/service/business/aggregator.js:46:11)
```

**Comment by jeffmcaffer** [comment]
fixed
