### ISSUE TITLE
Failed to fetch data through the API

### ISSUE THREAD

**Issue by pombredanne** [clearlydefined/service#675]
When doing some API tests I have been hitting this issue:
At some point I did hit that URL:
- https://api.clearlydefined.io/definitions?type=npm&provider=npmjs&continuationToken=bnBtL25wbWpzL0B6eGluZy9saWJyYXJ5LzAuNi4wLWJldGEuMQ==
- the `continuationToken` in that JSON was `"continuationToken":"bnBtL25wbWpzL0B+bGlzZmFuL2xvZ2dlci8xLjEuMC1iZXRhLjA="` (e.g. `npm/npmjs/@~lisfan/logger/1.1.0-beta.0` when base64-decoded)
(See attached payload [definitions.json.txt](https://github.com/clearlydefined/service/files/3888915/definitions.json.txt) )
- Following the continuation token and getting https://api.clearlydefined.io/definitions?type=npm&provider=npmjs&continuationToken=bnBtL25wbWpzL0B+bGlzZmFuL2xvZ2dlci8xLjEuMC1iZXRhLjA= yield exactly nothing at all... an empty page ( HTTP Status code: 200 OK )

The only odd thing in that seems to be the `@~lisfan` scope with tilde? Other than that it could be some CloudFlare thing?

**Comment by geneh** [comment]
Is it related to https://github.com/clearlydefined/service/issues/670?

**Comment by pombredanne** [comment]
@geneh I do not think this is related to #670 
#670 is more about some limit (possibly some partition of the DB or similar) that is hit without returning more records. There is no empty data returned there (just proper JSON, but less records than expected)
This is in contrast with here where there seems to be some things that choke since there is no data returned at all.

**Comment by pombredanne** [comment]
This is another example that returns empty data: 
https://api.clearlydefined.io/definitions?continuationToken=ZGViL2RlYmlhbi8tL2NvbmZpZy1wYWNrYWdlLWRldi81LjR+YnBvOSsxX2FsbA==

**Comment by pombredanne** [comment]
So since certain continuationTokens do not seems to work at all and we get no payload at all, paginated API usage is not possible ATM. The common issues seem to be when there s a `tilde` `~` in any part of the coordinates.
Here is a sample Python 3 script to reproduce.     Do `pip install requests` before using.

```
import base64
import io
import json
from os import path
import time

import requests


def fetch_sand_save_definitions(data_dir, api_url='https://api.clearlydefined.io/definitions/'):
    url = api_url
    counter = 0
    continuation =None
    while True:

        counter += 1
        coord =  str(base64.b64decode(continuation)) if continuation else ''
        print('Fetching:', url, 'to:', counter, 'continuation coordinates:', coord)

        payload = requests.get(url).json()
        definitions = payload['data']
        with io.open(path.join(data_dir, str(counter)), 'w') as output:
            json.dump(definitions, output)

        continuation = payload['continuationToken']
        if not continuation:
            break

        url = api_url + '?continuationToken={}'.format(continuation)

        # be polite
        time.sleep(0.5)


if __name__ == '__main__':
    import sys
    args = sys.argv[1:]
    fetch_sand_save_definitions(data_dir=args[0])
```

**Comment by pombredanne** [comment]
@jeffmcaffer FYI this is one of the bug that impairs mirroring

**Comment by pombredanne** [comment]
@MichaelTsengLZ FYI too

**Comment by nellshamrell** [comment]
Hi @pombredanne!

I'm doing a triage on all issues in the major ClearlyDefined repos. I'm trying to replicate this one. I ran your python script using python3 (and I did run `pip3 install requests`) and received this error:

```
nells@campusnell:~/random$ python3 script.py
Traceback (most recent call last):
  File "script.py", line 38, in <module>
    fetch_sand_save_definitions(data_dir=args[0])
IndexError: list index out of range
nells@campusnell:~/random$
```

Could you provide me some more info about how to replicate this issue?

Thank you!

**Comment by pombredanne** [comment]
Hi @nellshamrell !
The script needs an argument which is a directory where JSON will be saved.
Use it this way:  `Usage: script.py <directory path to were to save results>`

**Comment by nellshamrell** [comment]
Got it! Ty!

**Comment by nellshamrell** [comment]
Here are the results I got from the script:

* [Output](https://gist.github.com/nellshamrell/6b93d168eee038f20b41ca468d94a644)

Here's the most relevant chunk:

```bash
Fetching: https://api.clearlydefined.io/definitions/?continuationToken=ZGVic3JjL2RlYmlhbi8tL2NrcG9ydC8wLjF+cmMxLTc= to: 81 continuation coordinates: b'debsrc/debian/-/ckport/0.1~rc1-7'
Traceback (most recent call last):
  File "script.py", line 38, in <module>
    fetch_sand_save_definitions(data_dir=args[0])
  File "script.py", line 20, in fetch_sand_save_definitions
    payload = requests.get(url).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Looks like it's choking on `'debsrc/debian/-/ckport/0.1~rc1-7` which, as noted above, has a tilde `~` in the coordinates.

Going to call this reproducible - there's something happening when trying to follow a continuation token to coordinates that include a '~' in them.
